# Generated by Django 4.1.1 on 2022-10-06 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='Family',
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='family',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='info.family'),
        ),
    ]
